name: Apex PMD Analysis

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download PMD
        run: |
          curl -L -o pmd-bin.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
          unzip -o pmd-bin.zip

      - name: Run PMD on Apex classes
        run: |
          ./pmd-bin-6.55.0/bin/run.sh pmd \
            -d force-app/main/default/classes \
            -R category/apex/design.xml \
            -R category/apex/bestpractices.xml \
            -R category/apex/errorprone.xml \
            -f html \
            -r pmd-report.html

      - name: Upload PMD Report
        uses: actions/upload-artifact@v3
        with:
          name: pmd-report
          path: pmd-report.html
